import { CountSession, InventoryItem, SystemImageResource } from './types';

export const mobileAppIconUrl = '/app-icon.jpg';

export const SYSTEM_IMAGES: SystemImageResource[] = [
  {
    id: 'app-mobile-icon',
    title: 'Ícone Oficial do App Móvel',
    description: 'Símbolo gráfico puro sem texto para instalação do aplicativo no celular e coletor.',
    url: mobileAppIconUrl,
    type: 'logo',
    tag: 'App Móvel Celular',
  },
  {
    id: 'ceva-logo',
    title: 'Logo Oficial CEVA Logistics',
    description: 'Logotipo vetorial padrão utilizado no cabeçalho do WMS e relatórios oficiais.',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDjrey_kwGpR-crxu_Ds9cwMt1reNddBlhuIkJvr6edGVy5qoHErwCRZHLnQRtPEVbkmsKO-zh5djTQC3kkyBIE6FNNlBOP6o9ynJdkOMLqUdJx75q7bYyzEb2Mhct0NMN8j5az6J6R9qu-txSVgfNE2XGm2uO69QSameHozxfed44H_wdk6DRzKLTu2xPe94tbk0Jra4s3WpFGwKeRMN-jJMpKYrFseVPR8WzIqb_iLMuMI4kxcK4',
    type: 'logo',
    tag: 'Identidade Visual',
  },
  {
    id: 'layout-ref',
    title: 'Layout Original do Sistema',
    description: 'Captura e documentação visual de referência do Dashboard de Inventário.',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCkRMxyx_cghjuoVf6Fl-TAcL3l_HTEQ8Tax014AIpJgCPNR2CPTexq0RqnOShT81NwGI8MZSTPsG1KloDWaHHMgh1wwQJNoD1wDGsc6ZbsRacRsA3yVG3oYgBzcEfepvjDpDRi8i3-0g_bt67p5W-4LK5spdsEc5BxAK5BvGA7D0hXzyugeFLV6XrGUXNHRC5ApAQUo7f14YPHUZ5f2aZsIlJ7a5H8JCRHYF1qG2XmMhUiyWZjmn9irECta8eyeEnkuA',
    type: 'layout_ref',
    tag: 'Documentação Visual',
  },
  {
    id: 'prod-auto-01',
    title: 'Módulo Eletrônico Automotivo Bosch ECU',
    description: 'Componente eletrônico de controle de injeção direta em caixa antiestática.',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'product',
    tag: 'SKU #AUTO-9921',
  },
  {
    id: 'prod-auto-02',
    title: 'Sensor de Pressão Common Rail Delphi',
    description: 'Peça automotiva de alta precisão para linha pesada.',
    url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    type: 'product',
    tag: 'SKU #AUTO-4412',
  },
  {
    id: 'prod-auto-03',
    title: 'Pallet Caixa KLT CEVA 600x400',
    description: 'Caixas plásticas padrão automotivo para movimentação e armazenagem vertical.',
    url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    type: 'product',
    tag: 'SKU #LOG-8820',
  }
];

export const INITIAL_ITEMS: InventoryItem[] = [
  {
    id: 'itm-01',
    sku: 'AUTO-9921',
    name: 'Módulo Eletrônico ECU Bosch Bosch-V4',
    barcode: '7891234567890',
    category: 'Linha Automotiva',
    expectedQty: 50,
    countedQty: 50,
    unit: 'UN',
    location: 'RUA-04-PREDIO-B-N3',
    batch: 'LOT-2026-A1',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    status: 'ok',
  },
  {
    id: 'itm-02',
    sku: 'AUTO-4412',
    name: 'Sensor de Pressão Common Rail Delphi',
    barcode: '7894412009812',
    category: 'Linha Automotiva',
    expectedQty: 30,
    countedQty: 28,
    unit: 'UN',
    location: 'RUA-04-PREDIO-B-N1',
    batch: 'LOT-2026-C4',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    status: 'divergent',
    discrepancyReason: 'Falta física (-2 UN) detectada no endereço de picking.',
  },
  {
    id: 'itm-03',
    sku: 'LOG-8820',
    name: 'Caixa KLT Retornável 600x400x280',
    barcode: '7898820114455',
    category: 'Embalagens & Logística',
    expectedQty: 62,
    countedQty: 62,
    unit: 'CX',
    location: 'DOCA-12-PULMAO',
    batch: 'LOT-CEVA-2026',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    status: 'ok',
  },
  {
    id: 'itm-04',
    sku: 'ELET-1090',
    name: 'Leitor Óptico Handheld Zebra DS2208',
    barcode: '7891090223344',
    category: 'Equipamentos TI/WMS',
    expectedQty: 10,
    countedQty: 9,
    unit: 'UN',
    location: 'SALA-TI-ARMARIO-02',
    batch: 'PAT-2026-IT',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    status: 'divergent',
    discrepancyReason: '1 unidade em manutenção externa sem baixa no WMS.',
  },
  {
    id: 'itm-05',
    sku: 'MEC-3310',
    name: 'Kit Rolamento de Eixo Traseiro SKF',
    barcode: '7893310778899',
    category: 'Linha Pesada',
    expectedQty: 25,
    countedQty: 25,
    unit: 'KIT',
    location: 'RUA-02-PREDIO-A-N4',
    batch: 'LOT-SKF-09',
    imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=600&q=80',
    status: 'ok',
  },
  {
    id: 'itm-06',
    sku: 'QUIM-5501',
    name: 'Fluido de Freio DOT 4 Sintético 500ml',
    barcode: '7895501332211',
    category: 'Químicos & Fluidos',
    expectedQty: 40,
    countedQty: 40,
    unit: 'FR',
    location: 'RUA-07-PREDIO-Q-N1',
    batch: 'LOT-FLUID-26',
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80',
    status: 'ok',
  },
];

export const INITIAL_SESSIONS: CountSession[] = [
  {
    id: 'cnt-01',
    code: '#CNT-0309',
    name: 'teste leticia',
    responsible: 'Letícia M.',
    date: '03/09/2026',
    status: 'Concluída',
    sector: 'Setor Letícia - Doca 08',
    itemsCount: 3,
    type: 'Amostragem',
    createdAt: '2026-09-03T10:15:00',
    items: [
      INITIAL_ITEMS[0],
      INITIAL_ITEMS[2],
      INITIAL_ITEMS[4],
    ],
  },
  {
    id: 'cnt-02',
    code: '#CNT-0310',
    name: 'Contagem Cíclica - Setor A',
    responsible: 'Rogério A.',
    date: '03/09/2026',
    status: 'Concluída',
    sector: 'Setor A (Racks 01 a 08)',
    itemsCount: 86,
    type: 'Cíclica',
    createdAt: '2026-09-03T08:30:00',
    items: [
      INITIAL_ITEMS[0],
      INITIAL_ITEMS[2],
      INITIAL_ITEMS[4],
      INITIAL_ITEMS[5],
    ],
  },
  {
    id: 'cnt-03',
    code: '#CNT-0311',
    name: 'Auditoria Pallets Linha Automotiva',
    responsible: 'Auditoria WMS',
    date: '02/09/2026',
    status: 'Divergência',
    sector: 'Pulmão Automotivo Doca 12',
    itemsCount: 42,
    type: 'Auditoria',
    createdAt: '2026-09-02T14:20:00',
    items: [
      INITIAL_ITEMS[1],
      INITIAL_ITEMS[3],
      INITIAL_ITEMS[0],
    ],
  },
  {
    id: 'cnt-04',
    code: '#CNT-0308',
    name: 'Contagem Rotativa Geral',
    responsible: 'Terminal-WMS-SP',
    date: '01/09/2026',
    status: 'Concluída',
    sector: 'Geral - Centro Louveira',
    itemsCount: 11,
    type: 'Rotativa',
    createdAt: '2026-09-01T17:00:00',
    items: [
      INITIAL_ITEMS[2],
      INITIAL_ITEMS[5],
    ],
  },
];
